POST https://phonebook-407d.onrender.com/api/persons HTTP/1.1
content-type: application/json

{
  "name": "John Doe",
  "number": "1234567890"
}

###
POST https://phonebook-407d.onrender.com/api/persons HTTP/1.1
content-type: application/json

{
  "name": "Jane Smith"
}

###
POST https://phonebook-407d.onrender.com/api/persons HTTP/1.1
content-type: application/json

{
  "number": "9876543210"
}

###
DELETE https://phonebook-407d.onrender.com/api/persons/4